### PR TITLE
Dec 1118

### PR DESCRIPTION
**Pull request by jonhartzler**
i have travis, coveralls, hound and codeclimate.  Code climate works off master so we need to merge this pr to get it to start.

### CODE REVIEW

**Comment by jonhartzler** [comment]
When I started this branch hound was not pointing at the right style guide.  There is a violation i am just not sure which one is real so I am ignoring for now.

**Comment by danthewolfe** [comment]
👍

**Comment by rfox2** [comment]
👍

**Comment by jgondron** [comment]
👎

**Comment by jonhartzler** [comment]
ha too LATE @jgondron !!!

**Comment by danthewolfe** [comment]
@jonhartzler the appropriate response to a 👎  is 👊 .

**Pull request merged**
